version: '3'

services:
  mysql:
    image: mysql:8.0.30-debian
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      #MYSQL_DATABASE: imersao17
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql #executa o script db.sql ao subir o container
  app:
    build: .
    container_name: goapi
    volumes:
      - .:/go/src/
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'
    ports:
      - 8080:8080
    depends_on:
      - mysql
